### ISSUE TITLE
Fix signup bug

### ISSUE THREAD

**Issue by Mostafa-ewida** [Hack-Maze/backend-fastapi#40]
when calling signup api endpoint  gives Error 500 Internal Server Error

![Image](https://github.com/Hack-Maze/backend-fastapi/assets/71707534/3e2dad5e-ec5f-45bf-af44-dc474e2ae5e8)

when calling it again with the same data   gives duplicate data means that the user has been created 

![Image](https://github.com/Hack-Maze/backend-fastapi/assets/71707534/bdc23350-499c-4127-a0aa-d359455a46e0)

here are the logs, @IMperiumX 

```
10.244.1.65:36226 - "POST /api/v1/signup HTTP/1.1" 500
[2024-04-25 16:22:46 +0000] [10] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 315, in app
    content = await serialize_response(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': UserCreate(email='sdfsd@example.com', is_active=True, is_superuser=False, full_name='Mostafa Essam Ewida', password='changethissdfs'), 'url': 'https://errors.pydantic.dev/2.6/v/missing'}

10.244.1.65:41516 - "POST /api/v1/login/access-token HTTP/1.1" 200
10.244.1.65:41516 - "GET /api/v1/users/me HTTP/1.1" 200
```

**Comment by IMperiumX** [comment]
![Image](https://github.com/Hack-Maze/backend-fastapi/assets/72172663/4b1217e3-dce1-440c-903b-c443bb116a91)
